version: '3'
services:
  poll:
    build: poll
    ports:
      - "5000:80"
    networks:
      - poll-tier
    restart: always
    environment:
      - PORT=80
      - REDIS_HOSTNAME=redis
  redis:
    image: redis
    ports: ["6379"]
    networks:
      - poll-tier
      - back-tier
    restart: always
  worker:
    build: worker
    networks:
      - back-tier
    restart: always
    environment:
      - REDIS_HOSTNAME=redis
      - DB_HOSTNAME=db
  db:
    image: postgres
    networks:
      - result-tier
      - back-tier
    restart: always
    volumes:
      - postgres-volume
  result:
    build: result
    ports:
      - "5001:80"
    networks:
      - result-tier
    restart: always
    environment:
      - PORT=80
      - DB_HOSTNAME=db

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  postgres-volume:
