version: '3'
services:
  poll:
    build: poll
    ports:
      - "5000:80"
    networks:
      - poll-tier
    restart: always
  redis:
    image: redis
    ports: ["6379"]
    networks:
      - poll-tier
      - back-tier
    restart: always
  worker:
    build: worker
    networks:
      - back-tier
    restart: always
  db:
    image: postgres
    networks:
      - result-tier
      - back-tier
    restart: always
  result:
    build: result
    ports:
      - "5001:80"
    networks:
      - result-tier
    restart: always

networks:
  poll-tier:
  result-tier:
  back-tier:

